package com.sahha.notification.event;

public enum AppointmentEventType {
	APPOINTMENT_REQUESTED,
	APPOINTMENT_CONFIRMED,
	APPOINTMENT_REJECTED,
	APPOINTMENT_RESCHEDULED,
	APPOINTMENT_CANCELLED,
	APPOINTMENT_CHECKED_IN,
	APPOINTMENT_STARTED,
	APPOINTMENT_COMPLETED,
	APPOINTMENT_NO_SHOW
}
