package com.sahha.patient.entity;

public enum PatientAuditEventType {
	PATIENT_DUPLICATE_CHECKED,
	PATIENT_DIRECTORY_SEARCHED,
	PATIENT_ADMINISTRATIVE_PROFILE_VIEWED,
	PATIENT_REGISTERED,
	PATIENT_ADMINISTRATIVE_PROFILE_UPDATED
}
