package com.sahha.file.entity;

public enum FileAuditEventType {
	UPLOAD_NEGOTIATED,
	UPLOAD_STORED,
	UPLOAD_FAILED,
	SCAN_MARKED_CLEAN,
	SCAN_REJECTED,
	DOWNLOAD_GRANT_ISSUED,
	DOWNLOADED,
	ACCESS_DENIED,
	GRANT_EXPIRED
}
