spring.application.name=audit-service
spring.config.import=classpath:health-policy.properties
spring.cloud.config.enabled=${CONFIG_CLIENT_ENABLED:false}
server.port=${SERVER_PORT:8089}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true


spring.datasource.url=${AUDIT_DB_URL}
spring.datasource.username=${AUDIT_DB_USERNAME}
spring.datasource.password=${AUDIT_DB_PASSWORD}
spring.datasource.hikari.pool-name=SahhaAuditPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=3000

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true
