package com.sahha.scheduling.entity;

public enum AppointmentAuditEventType {
	APPOINTMENT_BOOKED,
	APPOINTMENT_CONFIRMED,
	APPOINTMENT_REJECTED,
	APPOINTMENT_RESCHEDULED,
	APPOINTMENT_CANCELLED,
	APPOINTMENT_CHECKED_IN,
	APPOINTMENT_STARTED,
	APPOINTMENT_COMPLETED,
	APPOINTMENT_NO_SHOW
}
