package com.sahha.auth.entity;

public enum SecurityEventType {
	ACCOUNT_REGISTERED,
	EMAIL_VERIFICATION_REQUESTED,
	EMAIL_VERIFIED,
	LOGIN_SUCCEEDED,
	LOGIN_DENIED,
	REFRESH_SUCCEEDED,
	REFRESH_DENIED,
	REFRESH_TOKEN_REUSE_DETECTED,
	SESSION_LIST_VIEWED,
	SESSION_REVOKED,
	ALL_SESSIONS_REVOKED,
	ACTIVE_ORGANISATION_SELECTED,
	PASSWORD_RESET_REQUESTED,
	PASSWORD_RESET_COMPLETED,
	PASSWORD_CHANGED,
	ACCOUNT_SUSPENDED,
	ACCOUNT_REACTIVATED,
	ACCOUNT_DISABLED
}
