package com.sahha.organisation.entity;

public enum OrganisationAuditEventType {
	ORGANISATION_CREATED,
	ORGANISATION_ADMIN_ASSIGNED,
	DEPARTMENT_CREATED,
	DEPARTMENT_UPDATED,
	DEPARTMENT_STATUS_CHANGED,
	STAFF_INVITATION_CREATED,
	STAFF_INVITATION_RENEWED,
	STAFF_INVITATION_REVOKED,
	STAFF_INVITATION_ACCEPTED,
	STAFF_INVITATION_REJECTED,
	STAFF_MEMBERSHIP_STATUS_CHANGED,
	STAFF_DEPARTMENT_ASSIGNED,
	STAFF_DEPARTMENT_ASSIGNMENT_ENDED,
	DOCTOR_PROFILE_CREATED,
	DOCTOR_PROFILE_UPDATED
}
