package com.sahha.scheduling.event;

import com.sahha.scheduling.entity.AppointmentAuditEventType;

public enum AppointmentDomainEventType {
	APPOINTMENT_REQUESTED,
	APPOINTMENT_CONFIRMED,
	APPOINTMENT_REJECTED,
	APPOINTMENT_RESCHEDULED,
	APPOINTMENT_CANCELLED,
	APPOINTMENT_CHECKED_IN,
	APPOINTMENT_STARTED,
	APPOINTMENT_COMPLETED,
	APPOINTMENT_NO_SHOW;

	public static AppointmentDomainEventType fromAudit(
			AppointmentAuditEventType auditType) {
		return switch (auditType) {
			case APPOINTMENT_BOOKED -> APPOINTMENT_REQUESTED;
			case APPOINTMENT_CONFIRMED -> APPOINTMENT_CONFIRMED;
			case APPOINTMENT_REJECTED -> APPOINTMENT_REJECTED;
			case APPOINTMENT_RESCHEDULED -> APPOINTMENT_RESCHEDULED;
			case APPOINTMENT_CANCELLED -> APPOINTMENT_CANCELLED;
			case APPOINTMENT_CHECKED_IN -> APPOINTMENT_CHECKED_IN;
			case APPOINTMENT_STARTED -> APPOINTMENT_STARTED;
			case APPOINTMENT_COMPLETED -> APPOINTMENT_COMPLETED;
			case APPOINTMENT_NO_SHOW -> APPOINTMENT_NO_SHOW;
		};
	}
}
